cynkra/constructive

R/data.frame.R, R/utils.R, tests/testthat/_snaps/data.frame.new.md, tests/testthat/test-data.frame.R
data.frame() messes with non syntactic names by default unless we set check.names to `FALSE`.
fixed by this PR
=> handle non syntactic names

R/numeric.R, tests/testthat/test-data.frame.R
We have a special way of handling numerics and it wasn't robust to NAs. Now it is.
We are consistent with other types in that we use explicit `NA_real_` only if a vector contains only NAs
=> handle na numerics

R/numeric.R, tests/testthat/_snaps/numeric.md, tests/testthat/test-numeric.R
round better, and if we cannot round correctly (issue with M1), use binary notation
See : https://stackoverflow.com/questions/72899973/printed-value-for-high-numbers-is-wronger-than-it-should
+ discussion on Rdevel
=> better rounding

R/function.R, tests/testthat/_snaps/function.md, tests/testthat/test-function.R
We now define function the standard `function() {}` way. This means by default we don't attempt to reproduce the environment nor the src_ref
=> Improve function support

R/function.R
Closes #71 
`identical(, ignore.srcref = TRUE)` is not enough, it might just look at the srcref attribute of the function, but there are more of them nested in the objects.
=> Use zap_scref() before comparing functions

DESCRIPTION, NEWS.md, R/constructive.R
Add news file and bump version to 0.0.1 so we can tag it and merge #56
=> Add news file

R/utils.R, tests/testthat/_snaps/dots.new.md, tests/testthat/_snaps/quosure.new.md, tests/testthat/_snaps/quosures.new.md
by using as.list.environment() rather than as.list()
=> make match2() more robust re envs

R/constructive.R, R/utils.R, tests/testthat/_snaps/others.md, tests/testthat/test-others.R
Closes #79
``` r
constructive::construct(list(pryr::partial, purrr::partial, purrr::map, purrr::map_dbl), data = c("pryr", "purrr", list(map = 1)))
#> list(pryr::partial, purrr::partial, purrr::map, map_dbl)
constructive::construct(list(1, 2), data = list(list(x=1), list(x=2)))
#> Error in `constructive::construct()`:
#> ! `data` must contain must one definition per name
#> ✖ Found duplicate definitions for `x`
#> Backtrace:
#>     ▆
#>  1. └─constructive::construct(list(1, 2), data = list(list(x = 1), list(x = 2)))
#>  2.   └─constructive:::preprocess_data(data) at constructive/R/constructive.R:65:2
#>  3.     └─rlang::abort(c(msg, x = info), call = parent.frame()) at constructive/R/constructive.R:141:6
```
<sup>Created on 2022-11-06 with [reprex …
=> handle conflicts in data

DESCRIPTION, R/constructive.R, R/environment.R, man/opts_environment.Rd, tests/testthat/_snaps/environment.md, tests/testthat/test-environment.R
Closes #76 
This solves issues of circularity but this breaks the principle of having a single call, and by doing so the constructed code creates variables
```
e <- new.env()
e$f <- e
foo <- evalq(~a, e)
construct(foo, opts_environment(predefine = TRUE), opts_formula(environment = TRUE))
#> .env.1.. <- new.env(parent = .GlobalEnv)
#> ..env.1..$f <- ..env.1..
#> (~a) |>
#>   structure(.Environment = ..env.1..)
```
=> predefine environments

R/construct-helpers.R, R/environment_utils.R, R/s3-language.R
=> chore: Use natural spacing in `expr()` calls

DESCRIPTION, R/abort.R, R/construct.R, R/construct_diff.R, R/roxygen2-tags.R, R/utils.R, tests/testthat/_snaps/s3-ggplot2-Coord.md, tests/testthat/test-abort.R, tests/testthat/test-construct_multi.R, tests/testthat/test-s3-ggplot2-Coord.R
Closes #229
After #199 
* We use {prettycode} only when it's installed
* We don't skip tests anymore if it's not installed
* {prettycode} moves from Imports to Suggests
=> Optional prettycode

R/s3-ggplot2-Scale.R, R/s3-ggplot2-theme.R, R/utils.R
For #265 
This solves the failure mentioned in the ticket and some more. But the snapshot will be different when the new version will be released.
@krlmlr how can we deal with that ? do we wait for the upcoming ggplot2 CRAN version to break constructive and release a new version soon after ? Do we release first a version that skips ggplot tests for ggplot >= 3.5 ? to then switch them back on on our next version ?
=> Adapt ggplot

NEWS.md, R/s3-tbl_df.R, man/construct.Rd, man/opts_tbl_df.Rd, tests/testthat/_snaps/s3-tbl_df.md, tests/testthat/test-s3-tbl_df.R
Very small new feature. In `tribble()` calls I usually right-justify so the commas all line up - this is now possible like so:
``` r
devtools::load_all()
#> ℹ Loading constructive
construct(
dplyr::band_instruments,
opts_tbl_df(constructor = "tribble")
)
#> tibble::tribble(
#>   ~name,   ~plays,
#>   "John",  "guitar",
#>   "Paul",  "bass",
#>   "Keith", "guitar",
#> )
construct(
dplyr::band_instruments,
opts_tbl_df(constructor = "tribble", justify = "right")
)
#> tibble::tribble(
#>     ~name,   ~plays,
#>    "John", "guitar",
#>    "Paul",   "bass",
#>   "Keith", "guitar",
#> )
```
<sup>Created on 2024-05-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
* Also adds support for `justification = "none"` and `justification = "centre"`
* Also adds a new snapshot test checking …
=> feat: add a `justify` argument to `opts_tbl_df()`

R/bypass.R, R/s3-dots.R, R/utils.R, man/opts_dots.Rd, tests/testthat/_snaps/s3-dots.md, tests/testthat/setup.R, tests/testthat/test-s3-dots.R
constructive was brittle if an object had a subclass not supported by constructive but with a `$` or `[[` method (or similar), now we override some internal generics, we should use the bypass package ultimately
=> bypass S3 methods

R/s3-data.frame.R, R/s3-data.table.R, R/s3-tbl_df.R, tests/testthat/_snaps/s3-data.frame.md, tests/testthat/test-s3-data.frame.R
So we fall back to list when the df contains columns named as the constructor's arguments (like "row.names" etc)
=> improve data.frame, tibble, data.table

R/construct_idiomatic.R, tests/testthat/_snaps/s3-array.md, tests/testthat/_snaps/s3-matrix.md, tests/testthat/_snaps/s3-mts.md, tests/testthat/test-s3-array.R, tests/testthat/test-s3-matrix.R, tests/testthat/test-s3-mts.R
they were constructed as a vector with a dim attribute, because the matrix method was only triggered when matrix was in the class.
=> classed matrices

R/s3-matrix.R
Fallout from https://github.com/cynkra/constructive/pull/468. Should have been caught by CI/CD, but wasn't: https://github.com/krlmlr/actions-sync/issues/43.
=> fix: Fix matrix construction for R 4.0

.github/dep-suggests-matrix.json, R/s3-data.frame.R, R/s3-data.table.R, R/s3-tbl_df.R, man/construct.Rd, man/opts_data.frame.Rd, man/opts_data.table.Rd, man/opts_tbl_df.Rd, tests/testthat/_snaps/construct_diff.md, tests/testthat/_snaps/construct_dput.md, tests/testthat/_snaps/encoding.md, tests/testthat/_snaps/s3-AsIs.md, tests/testthat/_snaps/s3-constructive_options.md, tests/testthat/_snaps/s3-data.frame.md, tests/testthat/_snaps/s3-data.table.md, tests/testthat/_snaps/s3-dm.md, tests/testthat/_snaps/s3-grouped_df.md, tests/testthat/_snaps/s3-rowwise_df.md, tests/testthat/_snaps/s3-tbl_df.md, tests/testthat/test-encoding.R, tests/testthat/test-s3-data.frame.R, tests/testthat/test-s3-data.table.R, tests/testthat/test-s3-tbl_df.R
Closes #470 
This will unfortunately break some valid snapshot tests but I think it's better to have this the default behavior. There is a `recycle = TRUE` arg to `opts_data.frame()`, `opts_tbl_df()`, `opts_data.table()` if this needs to be turned off (in that case this needs to be turned of individually for these various classes.
Since recycling relies on S3 subsetting we cannot guarantee that it works if we don't know the bracket method, so I made it work only for the main base classes. The list of supported classes can be extended however.
=> recycling and duplicate names in dfs

DESCRIPTION, NEWS.md, R/construct.R
Closes #486 
NB, I had some test failures when running locally, but I think they must be due to differences with my setup because they were all about where linebreaks are placed. Here's an example:
```
Failure ([test-s3-R6ClassGenerator.R:2:3](vscode-file://vscode-app/Applications/Positron.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html#)): R6Class
Snapshot of code has changed:
old                                                        | new                                                  
[54]     ),                                                     |     ),                                           [54]
[55]     private = list(                                        |     private = list(                              [55]
[56]       queue = list(), …
```
=> feat: show a console message when using construct_clip()

R/construct.R, R/construct_clip.R, man/constructive-package.Rd
=> construct_clip respects non default print modes
