R/POSIXct.R
R/generic_and_default.R

Forward the dots in POSIXct to handle `max_atomic = 0`

---

DESCRIPTION

Run `usethis::use_package("pixarfilms", "Suggests")`

---

R/POSIXct.R
R/POSIXlt.R
tests/testthat/_snaps/POSIXct.md
tests/testthat/_snaps/POSIXlt.md
tests/testthat/test-POSIXct.R
tests/testthat/test-POSIXlt.R

FIX NA handling in datetimes

---

R/data.frame.R
tests/testthat/_snaps/data.frame.md
tests/testthat/test-data.frame.R

B 21 fix zero row data.frames

---

R/constructive.R
R/generic_and_default.R
R/utils.R
man/construct.Rd

We were using `match()` which is surprisingly slow, so implemented an alternative.
We also allow unnamed elements in the data arg, in which case we recurse

improve data handling

---

R/deparse_call.R
tests/testthat/_snaps/deparse_call.md
tests/testthat/test-deparse_call.R

deparse colon ops correctly

---

R/quosure.R
R/quosures.R
tests/testthat/_snaps/quosure.md
tests/testthat/_snaps/quosures.md
tests/testthat/test-quosure.R
tests/testthat/test-quosures.R

Closes #33 
we use `as_quosure()` and `as_quosures()`, it seemed the most sensible constructor

Handle quosures

---

R/generic_and_default.R

fall back when S3 method not dispatched correctly

---

R/atomic.R
tests/testthat/_snaps/atomic.md
tests/testthat/test-atomic.R

handle empty names

---

R/factor.R
R/ordered.R
tests/testthat/_snaps/factor.md
tests/testthat/_snaps/ordered.md
tests/testthat/test-factor.R
tests/testthat/test-ordered.R

handle named factors

---

R/deparse_call.R
tests/testthat/_snaps/deparse_call.new.md

Handle quoted strings after dollar or at signs

---

R/s3-function.R
tests/testthat/_snaps/s3-function.md
tests/testthat/test-s3-function.R

Handle bodyless srcrefless functions

---

R/s3-rowwise_df.R
man/opts_tbl_df.Rd
tests/testthat/_snaps/s3-data.table.md
tests/testthat/_snaps/s3-rowwise_df.md
tests/testthat/test-s3-data.table.R
tests/testthat/test-s3-rowwise_df.R

handle rowwise dfs

---

R/deparse_call.R
R/utils.R
tests/testthat/_snaps/deparse_call.md
tests/testthat/test-deparse_call.R

Fix deparsing of non-syntactic argument names

---

R/s3-atomic.R
man/construct.Rd
man/opts_atomic.Rd
tests/testthat/_snaps/s3-atomic.md
tests/testthat/test-s3-atomic.R

Closes #138 
``` r
library(constructive)
construct(c("a", "a", "b", "c", "c", "c", "c"))
#> rep(c("a", "b", "c"), c(2L, 1L, 4L))
construct(c("a", "b", "a", "b","a", "b","a", "b"))
#> rep(c("a", "b"), 4)
construct(c("a", "a", "b", "b", "c", "c"))
#> rep(c("a", "b", "c"), each = 2L)
construct(c(1, 2, 3, 4, 1, 2, 3, 4))
#> rep(seq(1, 4, by = 1), 2)
construct(as.integer(c(1, 2, 3, 4, 1, 2, 3, 4)))
#> rep(1:4, 2)
construct(c(2, 4, 6, 8, 2, 4, 6, 8))
#> rep(seq(2, 8, by = 2), 2)
construct(as.integer(c(2, 4, 6, 8, 2, 4, 6, 8)))
#> rep(seq(2L, 8L, by = 2L), 2)
construct(c("a", "a", "b", "c", "c", "c", "c"), opts_atomic(compress = FALSE))
#> c("a", "a", "b", "c", "c", "c", "c")
```
<sup>Created on 2023-04-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

compress atomic vectors

---

R/s3-atomic.R
tests/testthat/_snaps/s3-atomic.md
tests/testthat/test-s3-atomic.R

named vectors are not compressed anymore

fix atomic vector compression

---

R/repair_attributes.R
tests/testthat/_snaps/repair_attributes.md
tests/testthat/test-repair_attributes.R

Handle structure()'s special arguments

---

R/repair_attributes.R
R/s3-function.R
tests/testthat/_snaps/abort.md
tests/testthat/_snaps/repair_attributes.md
tests/testthat/_snaps/s3-environment.md
tests/testthat/_snaps/s3-function.md
tests/testthat/_snaps/s3-ggplot2-Coord.md
tests/testthat/_snaps/s3-ggplot2-Scale.md
tests/testthat/_snaps/s3-ggplot2-ggplot.md

don't use match.fun

---

R/s3-atomic.R
tests/testthat/_snaps/s3-atomic.md
tests/testthat/test-s3-atomic.R

Support NaN

---

R/s3-data.frame.R
tests/testthat/_snaps/s3-data.frame.md
tests/testthat/test-s3-data.frame.R

Fix read.names

---

R/s3-data.table.R
man/construct.Rd
man/opts_data.table.Rd
tests/testthat/_snaps/s3-data.table.md
tests/testthat/test-s3-data.table.R

153 key in data.table

---

R/s3-atomic.R
man/construct.Rd
man/opts_atomic.Rd
tests/testthat/_snaps/abort.md
tests/testthat/_snaps/construct_multi.md
tests/testthat/_snaps/encoding.md
tests/testthat/_snaps/s3-AsIs.md
tests/testthat/_snaps/s3-array.md
tests/testthat/_snaps/s3-atomic.md
tests/testthat/_snaps/s3-factor.md
tests/testthat/_snaps/s3-matrix.md
tests/testthat/_snaps/s3-ordered.md

Character construction

---

R/register_constructors.R
R/s3-data.frame.R
R/s3-ggplot2-theme.R
R/utils.R
tests/testthat/_snaps/s3-data.frame.md
tests/testthat/test-s3-data.frame.R

corrupted df

---

R/repair_attributes.R
R/s3-atomic.R

Was necessary for some object.

Add NA check

---

R/construct-helpers.R
man/construct.Rd
tests/testthat/_snaps/s3-atomic.md
tests/testthat/_snaps/s3-ggplot2-Coord.md
tests/testthat/_snaps/s3-ggplot2-Scale.md
tests/testthat/_snaps/s3-list.md

Better error

---

R/s3-factor.R
R/s3-ordered.R
man/construct.Rd
man/opts_factor.Rd
man/opts_ordered.Rd
tests/testthat/_snaps/s3-factor.md
tests/testthat/_snaps/s3-ordered.md
tests/testthat/test-s3-factor.R
tests/testthat/test-s3-ordered.R

Support NA levels

---

R/construct.R
R/construct_diff.R
R/s3-environment.R
R/utils.R
man/construct.Rd
man/construct_diff.Rd
man/dot-cstr_repair_attributes.Rd

Otherwise users end up with non-parseable code.

fix: Default to magrittr pipe for R < 4.2

---

R/construct-helpers.R
R/deparse_call.R
R/s3-data.frame.R
R/s3-tbl_df.R
R/utils.R
tests/testthat/test-utils.R

even if we are (currently) styling the code.
For #49.

feat: Indent when constructing

---

tests/testthat/_snaps/s3-ggplot2-ggplot.md
tests/testthat/setup.R
tests/testthat/test-abort.R
tests/testthat/test-construct_multi.R
tests/testthat/test-s3-ggplot2-ggplot.R

test: Skip tests if packages not installed

---

R/deparse_call.R
tests/testthat/_snaps/deparse_call.md
tests/testthat/test-deparse_call.R

Correctly consstruct empty braced expression

---

R/opts.R
R/zzz.R

no need for constructive:: in `...`

---

DESCRIPTION

@krlmlr I should have done this before sorry for the oversight

Add Kirill as contributor

---

R/s3-atomic.R
tests/testthat/_snaps/s3-atomic.md
tests/testthat/test-s3-atomic.R

Handle big integer diffs

---

R/C_wrappers.R
R/construct.R
src/constructive.c
tests/testthat/_snaps/construct_multi.md
tests/testthat/test-construct_multi.R

Handle promises with construct_multi()

---

R/construct_idiomatic.R
tests/testthat/_snaps/s3-list.md
tests/testthat/test-s3-list.R

Use true length in .cstr apply

---

R/s3-formula.R
man/construct.Rd
man/opts_formula.Rd
tests/testthat/_snaps/s3-formula.md
tests/testthat/test-s3-formula.R

"next" constructor for formulas

---

R/s3-function.R
man/opts_function.Rd
tests/testthat/_snaps/s3-function.md
tests/testthat/test-s3-function.R

Handle non standard ast functions

---

R/s3-data.frame.R
tests/testthat/_snaps/s3-data.frame.md
tests/testthat/test-s3-data.frame.R

read.table constructor supports one_liner arg

---

R/s3-data.frame.R

Support classes without as.data.frame method

---

R/s3-atomic.R
tests/testthat/_snaps/s3-atomic.md
tests/testthat/test-s3-atomic.R

fix `escape`arg

---

R/deparse_call.R
man/deparse_call.Rd
tests/testthat/_snaps/deparse_call.md
tests/testthat/test-deparse_call.R

Add escape and unicode_representation args to deparse_call()

---

R/s3-ggplot2-theme.R

scrub x$axis.text.r$margin

---

R/s3-externalptr.R
tests/testthat/_snaps/s3-externalptr.md
tests/testthat/test-s3-externalptr.R

handle classed pointers

---

R/s3-dots.R
tests/testthat/_snaps/s3-dots.md
tests/testthat/test-s3-dots.R

handle classed dots

---

R/s4-classGeneratorFunction.R
tests/testthat/_snaps/s4.md

Use slots rather than representation

---

R/repair_attributes.R
R/s4.R
man/dot-cstr_repair_attributes.Rd
tests/testthat/_snaps/s4.md
tests/testthat/test-s4.R

deal with flagged S4 objects

---

NEWS.md
R/repair_attributes.R
tests/testthat/_snaps/s3-data.frame.md
tests/testthat/_snaps/s3-data.table.md
tests/testthat/_snaps/s3-tbl_df.md

improve attr repair

---

NEWS.md
R/abort.R

Don't fail on "try-error" objects

---

R/s3-function.R
R/s3-language.R
tests/testthat/_snaps/s3-function.md
tests/testthat/test-s3-function.R

support non syntactic formals

---

R/deparse_call.R
R/utils.R

fix names in language objects

---

R/environment_utils.R
R/s3-environment.R

fix environment attribute repair

---

R/s3-atomic.R
tests/testthat/_snaps/s3-atomic.md
tests/testthat/test-s3-atomic.R

Fix raw strings

---

R/deparse_call.R
tests/testthat/_snaps/deparse_call.md
tests/testthat/test-deparse_call.R

inline equal only when relevant

---

R/deparse_call.R
tests/testthat/_snaps/deparse_call.md
tests/testthat/test-deparse_call.R

Use right side assignment when relevant

---

R/s3-atomic.R
tests/testthat/_snaps/s3-atomic.md
tests/testthat/test-s3-atomic.R

improve complex number handling

---

R/s3-atomic.R
tests/testthat/_snaps/s3-atomic.md
tests/testthat/test-s3-atomic.R

handle negative zeroes

---

R/s3-ggplot2-theme.R

So it works after update, won't break old versions
Closes #397

Fix theme_bw 

---

R/C_wrappers.R
R/construct.R
R/s3-complex.R
src/constructive.c

hopefully this gets rid of the notes on r-devel

don't use non API functions

---

R/s3-character.R
R/s3-complex.R
R/s3-double.R
R/s3-expression.R
R/s3-integer.R
R/s3-list.R
R/s3-logical.R
R/s3-raw.R
R/utils.R
tests/testthat/_snaps/s3-atomic.md
tests/testthat/test-s3-atomic.R

repair names if attributes

---

R/abort.R
R/contains_self_reference.R
R/s3-environment.R
tests/testthat/_snaps/contains_self_reference.md
tests/testthat/test-contains_self_reference.R

Detect circularity

---

_pkgdown.yml
inst/template.R

pkg down reference

---

R/s3-atomic.R
inst/new_class_template_commented.R

It is correct in the non-commented template.

fix: Tweak generated code so that it works out of the box

---

NEWS.md
R/deparse_call.R
R/deparse_helpers.R
tests/testthat/_snaps/deparse_call.md
tests/testthat/test-deparse_call.R

deparse_call_impl() bug

---

DESCRIPTION
NEWS.md
R/bypass.R
cran-comments.md

bypass vapply

---

R/s3-tbl_df.R
tests/testthat/_snaps/s3-tbl_df.md
tests/testthat/test-s3-tbl_df.R

handle dates in tribble

---

R/deparse_call.R
tests/testthat/_snaps/deparse_call.md
tests/testthat/test-deparse_call.R

improve support for non syntactic function calls

---

R/s3-data.frame.R
R/s3-data.table.R
R/s3-tbl_df.R
tests/testthat/_snaps/s3-data.frame.md
tests/testthat/_snaps/s3-data.table.md
tests/testthat/_snaps/s3-tbl_df.md
tests/testthat/test-s3-data.frame.R
tests/testthat/test-s3-data.table.R
tests/testthat/test-s3-tbl_df.R

Closes #502.
Could there be other edge cases where renaming is necessary?

fix: Correct construction of unnamed data frames

---

R/s3-numeric_version.R
tests/testthat/_snaps/s3-numeric_version.md
tests/testthat/test-s3-numeric_version.R

fix version vectors

---

R/s3-bibentry.R
R/s3-citationFooter.R
R/s3-citationHeader.R
R/s3-difftime.R
R/s3-error.R
R/s3-function.R
R/s3-ggplot2-ggplot.R
R/s3-ggplot2-uneval.R
R/s3-hexmode.R
R/s3-noquote.R
R/s3-octmode.R
R/s3-person.R
R/s3-simpleCondition.R
R/s3-simpleError.R
R/s3-simpleMessage.R
R/s3-simpleWarning.R
R/s3-warning.R
tests/testthat/_snaps/s3-difftime.md
tests/testthat/test-s3-difftime.R

forward pipe and opt arg correctly
